@Library('sharedlibrary_cicd')_

pipeline
{
    agent any
    stages
    {
        stage('Downloaddddddd_loans')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Buildddddd_loans')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        }
        stage('Deploymentttttt_loans')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("DeclarativePipelinewithSharedLibraries","172.31.30.119","test1")
                }
            }
        }
    }
}

